---
permalink: online-help/reference-relationship-last-1-month-transfer-status-view.html 
sidebar: sidebar 
keywords:  
summary: Relationship：Last 1 month Transfer Statusビューを使用すると、非同期関係にあるボリュームについて、一定期間のボリューム転送の傾向を分析できます。また、このページにはボリューム転送が成功したか失敗したかが表示されます。 
---
= 関係：過去 1 カ月の転送ステータス画面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Relationship：Last 1 month Transfer Statusビューを使用すると、非同期関係にあるボリュームについて、一定期間のボリューム転送の傾向を分析できます。また、このページにはボリューム転送が成功したか失敗したかが表示されます。

ページの上部にあるコントロールを使用すると、特定のビュー（健常性、パフォーマンス、容量など）の選択、特定のオブジェクトの検索、フィルタの作成と適用による表示データのリストの絞り込み、ページの列の追加と削除/並べ替え、ページ上のデータをにエクスポートします `.csv`、 `.pdf`または `.xlsx` ファイル。カスタマイズしたページをカスタムビューとして保存し、データのレポートを定期的に生成して E メールで送信するようにスケジュール設定できます。

* * ソースボリューム *
+
ソースボリューム名が表示されます。

* * デスティネーションボリューム *
+
デスティネーションボリューム名が表示されます。

* * 操作タイプ *
+
ボリューム転送のタイプが表示されます。

* * 操作結果 *
+
ボリューム転送が成功したかどうかが表示されます。

* * 転送開始時間 *
+
ボリューム転送の開始時間が表示されます。

* * 転送終了時間 *
+
ボリューム転送の終了時間が表示されます。

* * 転送時間 *
+
ボリューム転送が完了するまでの所要時間（時間）が表示されます。

* * 転送サイズ *
+
転送されたボリュームのサイズ（ MB ）が表示されます。

* * ソース SVM *
+
Storage Virtual Machine （ SVM ）名が表示されます。

* * ソースクラスタ *
+
ソースクラスタ名が表示されます。

* * デスティネーション SVM *
+
デスティネーション SVM 名が表示されます。

* * デスティネーションクラスタ *
+
デスティネーションクラスタ名が表示されます。


