---
permalink: online-help/task-creating-the-volume-where-backups-are-stored.html 
sidebar: sidebar 
keywords:  
summary: ONTAP System ManagerまたはONTAP CLIを使用して、ONTAP クラスタのいずれかにSnapshotバックアップを格納するボリュームを作成できます。 
---
= バックアップが格納されるボリュームを作成しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System ManagerまたはONTAP CLIを使用して、ONTAP クラスタのいずれかにSnapshotバックアップを格納するボリュームを作成できます。



== 作業を開始する前に

クラスタ、 Storage VM 、およびボリュームが次の要件を満たしている必要があります。

* クラスタの要件：
+
** ONTAP 9.3 以降がインストールされている必要があります
** Unified Manager サーバに地理的に近い場所に配置する必要があります
** Unified Manager で監視できますが、必須ではありません


* Storage VM の要件：
+
** CIFS / SMBサービスまたはNFSサービスが有効になっている必要があります
** ネームスイッチとネームマッピングは「 files 」を使用するように設定する必要があります。
** NFSサーバでNFSv4が有効になっていて、クライアントとStorage VMでNFSv4 iddomainが指定されている必要があります
** クライアント側ユーザに対応するように作成されたローカルユーザ
** すべての読み取り / 書き込みアクセスが選択されていることを確認します
** エクスポートポリシーで Superuser Access が「 any 」に設定されていることを確認します


* ボリューム要件：
+
** ボリュームのサイズは、 Unified Manager /opt/NetApp/data ディレクトリのサイズの少なくとも 2 倍にする必要があります
+
コマンドを使用します `du -sh /opt/netapp/data/` 現在のサイズを確認します。

** セキュリティ形式は UNIX に設定する必要があります
** ローカル Snapshot ポリシーを無効にする必要があります
** ボリュームのオートサイズを有効にする必要があります
** パフォーマンス・サービス・レベルは 'Extreme など ' 高い IOPS と低い遅延を持つポリシーに設定する必要があります






== このタスクについて

NFS ボリュームの作成手順の詳細については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["ONTAP 9 で NFSv4 を設定する方法"] および http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["ONTAP 9 NFS 構成エクスプレスガイド"]。
