---
settings:
  name: Active IQ Unified Manager 9.8
  internal:
    pdf-enabled: true
    lipi-enabled: false
  prod:
    pdf-enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager の略
    url: "/active-iq-unified-manager-98"
    version-number: '9.8'
  - name: Unified Manager の略
    url: "/active-iq-unified-manager-99"
    version-number: '9.9'
  - name: Unified Manager の略
    url: "/active-iq-unified-manager-97"
    version-number: '9.7'
  - name: Unified Manager の略
    url: "/oncommand-unified-manager-95"
    version-number: '9.5'
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.8のドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/release-notes.html"
  - title: はじめに
    entries:
    - title: VMware vSphere のクイックスタートインストール
      url: "/qsg-vapp.html"
    - title: Linux のクイックスタートインストール
      url: "/qsg-linux.html"
    - title: Windows のクイックスタートインストール
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: リリースノート
      url: "/release-notes.html"
    - title: VMware vSphere のクイックスタートインストール
      url: qsg-vapp.html
    - title: Linux のクイックスタートインストール
      url: qsg-linux.html
    - title: Windows のクイックスタートインストール
      url: qsg-windows.html
  - title: configure Unified Manager をインストールします
    links:
    - title: VMware vSphere システムにアップグレードをインストールします
      url: install-vapp/concept-requirements-for-installing-unified-manager.html
    - title: Linux システムにアップグレードをインストール
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Windows システムにアップグレードをインストールします
      url: install-windows/concept-requirements-for-installing-unified-manager.html
    - title: Unified Manager を設定します
      url: config/concept-configuring-unified-manager.html
  - title: パフォーマンスの監視
    links:
    - title: パフォーマンスしきい値
      url: performance-checker/concept-managing-performance-thresholds.html
    - title: クラスタのパフォーマンス
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: QoS ポリシーグループ
      url: performance-checker/concept-managing-performance-using-qos-policy-group-information.html
  - title: データ保護の監視
    links:
    - title: 保護関係をセットアップする
      url: "/data-protection/task-setting-up-protection-relationships-in-unified-manager.html"
    - title: フェイルオーバーとフェイルバックを実行
      url: "/data-protection/task-performing-a-protection-relationship-failover-and-failback.html"
    - title: 保護関係を管理する
      url: "/data-protection/concept-managing-and-monitoring-protection-relationships.html"
    - title: レポートを生成します
      url: "/reporting/concept-unified-manager-reporting.html"
  - title: REST APIs を使用します
    links:
    - title: はじめに
      url: "/api-automation/concept-api-url-and-categories.html"
    - title: Active IQ Unified Manager での REST API へのアクセスおよび認証
      url: "/api-automation/concept-rest-api-access-and-authentication-in-oncommand-api-services.html"
    - title: ONTAP API にアクセスします
      url: "/api-automation/concept-gateway-apis.html"
  - title: リソースの追加
    links:
    - title: Unified Manager のビデオ
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Unified Manager のブログです
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish-date-mktg%20descending&layout=card&f:@facet-language-mktg=[English]
    - title: Active IQ Unified Manager の最新バージョンのドキュメント
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
