---
permalink: reporting/concept-unified-manager-reporting.html 
sidebar: sidebar 
keywords:  
summary: Active IQ Unified Manager \（旧OnCommand Unified Manager \）では、ONTAP ストレージシステムのレポートを表示、カスタマイズ、ダウンロード、およびスケジュール設定できます。レポートには、ストレージシステムの容量、健全性、パフォーマンス、保護関係に関する詳細を表示できます。 
---
= Unified Manager のレポート機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager （旧 OnCommand Unified Manager ）では、 ONTAP ストレージシステムのレポートを表示、カスタマイズ、ダウンロード、およびスケジュール設定できます。レポートには、ストレージシステムの容量、健全性、パフォーマンス、保護関係に関する詳細を表示できます。

Active IQ Unified Manager 9.6 で導入された新しい Unified Manager レポート作成機能およびスケジュール設定機能は、 Unified Manager バージョン 9.5 で廃止された以前のレポート作成エンジンに代わるものです。

レポート機能は、ネットワークのさまざまなビューを提供し、容量、健全性、パフォーマンス、保護データに関する実用的な情報を提供します。列の表示、非表示、再配置、データのフィルタリング、データのソート、 検索結果を表示します。カスタムビューは、再利用できるように保存したり、レポートとしてダウンロードしたりできます。また、定期的なレポートとしてスケジュールを設定して、 E メールで配布することもできます。

Active IQ Unified Manager 9.8 以降では、 Microsoft ® Excel 形式のビューをダウンロードしてカスタマイズできます。複雑な並べ替え、レイヤーフィルター、ピボットテーブル、グラフなど、 Excel の高度な機能を使用できます。結果の Excel レポートに問題がなければ、レポートがスケジュールされて共有されるたびに使用する Excel ファイルをアップロードできます。
