---
permalink: health-checker/concept-configuring-the-destination-and-schedule-for-database-dump-backups.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager のデータベースダンプバックアップ設定で、データベースのバックアップパス、保持数、およびバックアップスケジュールを設定できます。日単位または週単位のスケジュールされたバックアップを有効にすることができますデフォルトでは、スケジュールされたバックアップは無効になっていますが、バックアップスケジュールを設定する必要があります。 
---
= データベースダンプバックアップのデスティネーションの設定とスケジュール設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager のデータベースダンプバックアップ設定で、データベースのバックアップパス、保持数、およびバックアップスケジュールを設定できます。日単位または週単位のスケジュールされたバックアップを有効にすることができますデフォルトでは、スケジュールされたバックアップは無効になっていますが、バックアップスケジュールを設定する必要があります。



== 作業を開始する前に

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* バックアップパスとして定義する場所に 150GB 以上の利用可能なスペースが必要です。
+
Unified Manager ホストシステムとは別のリモートの場所を使用することを推奨します。

* Unified ManagerをLinuxシステムにインストールしている場合は、「jboss」ユーザにバックアップディレクトリへの書き込み権限が割り当てられていることを確認してください。
* 新しいクラスタの追加後にUnified Managerで15日分の履歴パフォーマンスデータを収集している間は、バックアップ処理を実行しないようにスケジュールしてください。




== このタスクについて

初回のバックアップではフルバックアップが実行されるため、 2 回目以降のバックアップよりも時間がかかります。フルバックアップは 1GB を超えることもあり、 3~4 時間かかる場合があります。2 回目以降のバックアップは増分バックアップとなり、所要時間は短くなります。

[NOTE]
====
増分バックアップファイルがバックアップ用に割り当てたスペースに対して増えすぎている場合は、新しいフルバックアップを定期的に作成して、古いフルバックアップとそのすべての子増分ファイルを置き換えることができます。Unified Manager が Linux システムにインストールされている場合は、別の方法として NetApp Snapshot のバックアップを開始することもできます。

====


== 手順

. 左側のナビゲーションペインで、 * General * > * Database Backup * をクリックします。
. [* データベース・バックアップ * ] ページで、 [ * バックアップ設定 * ] をクリックします。
. バックアップパス、保持数、およびスケジュールの値を設定します。
+
保持数のデフォルト値は 10 です。バックアップを無制限に作成する場合は 0 に設定します。

. 「毎日スケジュール」または「毎週スケジュール」 * ボタンを選択し、スケジュールの詳細を指定します。
. [ 適用（ Apply ） ] をクリックします。




== 結果

スケジュールに基づいてデータベースダンプバックアップファイルが作成されます。使用可能なバックアップファイルは、 [ データベースバックアップ ] ページに表示されます。

* 関連情報 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_start_a_new_Incremental_Backup_chain_within_ActiveIQ_Unified_Manager_versions_7.2_through_9.6["Active IQ Unified Manager 内で新しい増分バックアップ・チェーンを開始する方法"]
